'''The func function uses the while loop to add random integers generated by randint to the
random_indices list. It then uses the for loop to remove items from the list parameter based on an
index corresponding to values in the ramdom_indices list. The accept_input function prompts the user to
enter a number and ensures it is between 1 and 6'''

import random


def func(inp_list, value):
    random_indices = []
    i = value
    while i > 0:
        index = random.randint(1, 4)
        random_indices.append(index)
        i -= 1

    for index in random_indices:
        inp_list.pop(index)
    
    return tuple(inp_list)

def accept_inp():
    print("Enter number of items to be deleted. Enter number between 2 and 6", end=":")
    value  = int(input())
    if value > 6 or value < 2:
        print("Wrong value entered.")
        return accept_inp()
    else:
        return value

def main():
    inp_tokens = input("Enter at least 12 words/numbers separated by spaces>> ").split()
    max_range = accept_inp()
    print("Original List:",inp_tokens)
    result_tuple = func(inp_tokens, max_range)
    print("Result tuple:",result_tuple)

main()